language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

addons:
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6

sudo: required

cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer config -g github-oauth.github.com $GITHUB_TOKEN
  - travis_retry composer global require "fxp/composer-asset-plugin:1.2.*"
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
  - mysql -e 'CREATE DATABASE yii2_gii_plus_tests;'
  - tests/yii migrate --interactive=0
  - tests/yii gii/base_model --enableI18N=1 --interactive=0
  - tests/yii gii/custom_model --interactive=0
  - tests/yii gii/base_model --enableI18N=1 --interactive=0 --overwrite=1
  - tests/yii gii/base_model --enableI18N=1 --interactive=0 --overwrite=1
  - tests/yii gii/fixture --interactive=0
  - tests/yii gii/fixture --interactive=0 --overwrite=1

script:
  - vendor/bin/phpunit
